# Generated by Django 4.2.21 on 2025-05-30 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('part', '0135_alter_part_link'),
        ('stock', '0116_alter_stockitem_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartProvisioningData',
            fields=[
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='provisioning_data', serialize=False, to='part.part')),
                ('provisioning_status', models.CharField(choices=[('not_started', 'Not Started'), ('success', 'Success'), ('failed', 'Failed')], default='not_started', help_text='Status of the provisioning process for this part type or template', max_length=20, verbose_name='Provisioning Status')),
                ('imei', models.CharField(blank=True, help_text='Default or template IMEI, if applicable for this part type. Specific IMEIs for stock items should be handled differently if needed.', max_length=50, null=True, verbose_name='IMEI (template/default)')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Part Provisioning Data',
                'verbose_name_plural': 'Part Provisioning Data',
            },
        ),
        migrations.CreateModel(
            name='ProvisioningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('message', models.TextField(blank=True, help_text='Log message or error details', verbose_name='Message')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisioning_logs', to='stock.stockitem', verbose_name='Stock Item')),
            ],
            options={
                'verbose_name': 'Provisioning Log',
                'verbose_name_plural': 'Provisioning Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
